Repository AdopseTeam/IMDB, pull requests merged in 2021-03, with the labels that each got.

#10 Added electron support
  Data/MvcActorContext.cs
  Data/MvcMovieContext.cs
  Data/MvcSeriesContext.cs
  IMDB.csproj
  Program.cs
  Properties/launchSettings.json
  Startup.cs
  electron.manifest.json
Labels: Level 5, enhancement

#16 Fix actor view,controller,model
  Controllers/ActorController.cs
  Data/MvcActorContext.cs
  Views/Actor/Details.cshtml
Labels: bug, good first issue

#13 Create Readme
  README.md
Labels: Level 1, documentation

#17 Fixed Typo Connection String
  appsettings.json
Labels: bug, good first issue
